//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generated
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills/", IsNullable=true)]
    public partial class PaymentDocumentExportType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/account-base/")]
        public string AccountGuid { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills-base/")]
        public string PaymentDocumentNumber { get; set; } 
        
        /// <remarks/>
        public PaymentDocumentExportTypeAddressInfo AddressInfo { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CapitalRepairCharge", typeof(CapitalRepairType))]
        [System.Xml.Serialization.XmlElementAttribute("CapitalRepairDebt", typeof(DebtType))]
        [System.Xml.Serialization.XmlElementAttribute("ChargeDebt", typeof(PaymentDocumentExportTypeChargeDebt))]
        [System.Xml.Serialization.XmlElementAttribute("ChargeInfo", typeof(PDServiceChargeExportType))]
        [System.Xml.Serialization.XmlElementAttribute("Insurance", typeof(PaymentDocumentExportTypeInsurance))]
        [System.Xml.Serialization.XmlElementAttribute("PenaltiesAndCourtCosts", typeof(PaymentDocumentExportTypePenaltiesAndCourtCosts))]
        public object[] Items { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Expose", typeof(bool))]
        [System.Xml.Serialization.XmlElementAttribute("Withdraw", typeof(bool))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public bool Item { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName { get; set; } 
        
        /// <remarks/>
        public decimal DebtPreviousPeriods { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DebtPreviousPeriodsSpecified { get; set; } 
        
        /// <remarks/>
        public decimal AdvanceBllingPeriod { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdvanceBllingPeriodSpecified { get; set; } 
        
        /// <remarks/>
        public decimal totalPiecemealPaymentSum { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalPiecemealPaymentSumSpecified { get; set; } 
        
        /// <remarks/>
        public sbyte PaymentsTaken { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PaymentsTakenSpecified { get; set; } 
        
        /// <remarks/>
        public string AdditionalInformation { get; set; } 
        
        /// <remarks/>
        public decimal TotalPayableByPD { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalPayableByPDSpecified { get; set; } 
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class PaymentDocumentExportTypeAddressInfo
    {
        
        /// <remarks/>
        public sbyte LivingPersonsNumber { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LivingPersonsNumberSpecified { get; set; } 
        
        /// <remarks/>
        public decimal ResidentialSquare { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResidentialSquareSpecified { get; set; } 
        
        /// <remarks/>
        public decimal HeatedArea { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HeatedAreaSpecified { get; set; } 
        
        /// <remarks/>
        public decimal TotalSquare { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalSquareSpecified { get; set; } 
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class PDServiceDebtType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalService", typeof(PDServiceDebtTypeAdditionalService))]
        [System.Xml.Serialization.XmlElementAttribute("HousingService", typeof(PDServiceDebtTypeHousingService))]
        [System.Xml.Serialization.XmlElementAttribute("MunicipalService", typeof(PDServiceDebtTypeMunicipalService))]
        public ServiceDebtType Item { get; set; } 
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class PDServiceDebtTypeAdditionalService : ServiceDebtType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class ServiceDebtType : DebtType
    {
        
        /// <remarks/>
        public nsiRef ServiceType { get; set; } 
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/nsi-base/")]
    public partial class nsiRef
    {
        
        /// <remarks/>
        public string Code { get; set; } 
        
        /// <remarks/>
        public string GUID { get; set; } 
        
        /// <remarks/>
        public string Name { get; set; } 
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceDebtType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class DebtType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Month", typeof(int), Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        [System.Xml.Serialization.XmlElementAttribute("Year", typeof(short), Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        [System.Xml.Serialization.XmlElementAttribute("TotalPayable", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("TotalSumDebtPayable", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("orgPPAGUID", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName { get; set; } 
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills/", IncludeInSchema=false)]
    public enum ItemsChoiceType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://dom.gosuslugi.ru/schema/integration/base/:Month")]
        Month,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://dom.gosuslugi.ru/schema/integration/base/:Year")]
        Year,
        
        /// <remarks/>
        TotalPayable,
        
        /// <remarks/>
        TotalSumDebtPayable,
        
        /// <remarks/>
        orgPPAGUID,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class PDServiceDebtTypeHousingService : ServiceDebtType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MunicipalResource")]
        public PDServiceDebtTypeHousingServiceMunicipalResource[] MunicipalResource { get; set; } 
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class PDServiceDebtTypeHousingServiceMunicipalResource
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TotalPayable", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("TotalSumDebtPayable", typeof(decimal))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public decimal Item { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName { get; set; } 
        
        /// <remarks/>
        public nsiRef ServiceType { get; set; } 
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills/", IncludeInSchema=false)]
    public enum ItemChoiceType
    {
        
        /// <remarks/>
        TotalPayable,
        
        /// <remarks/>
        TotalSumDebtPayable,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class PDServiceDebtTypeMunicipalService : ServiceDebtType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class CapitalRepairType
    {
        
        /// <remarks/>
        public decimal Contribution { get; set; } 
        
        /// <remarks/>
        public decimal AccountingPeriodTotal { get; set; } 
        
        /// <remarks/>
        public decimal MoneyRecalculation { get; set; } 
        
        /// <remarks/>
        public decimal MoneyDiscount { get; set; } 
        
        /// <remarks/>
        public decimal TotalPayable { get; set; } 
        
        /// <remarks/>
        public string orgPPAGUID { get; set; } 
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class ServiceInformationType
    {
        
        /// <remarks/>
        public decimal individualConsumptionCurrentValue { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool individualConsumptionCurrentValueSpecified { get; set; } 
        
        /// <remarks/>
        public decimal houseOverallNeedsCurrentValue { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool houseOverallNeedsCurrentValueSpecified { get; set; } 
        
        /// <remarks/>
        public decimal houseTotalIndividualConsumption { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool houseTotalIndividualConsumptionSpecified { get; set; } 
        
        /// <remarks/>
        public decimal houseTotalHouseOverallNeeds { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool houseTotalHouseOverallNeedsSpecified { get; set; } 
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class ServiceChargeType
    {
        
        /// <remarks/>
        public decimal MoneyRecalculation { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MoneyRecalculationSpecified { get; set; } 
        
        /// <remarks/>
        public decimal MoneyDiscount { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MoneyDiscountSpecified { get; set; } 
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class ServicePDType
    {
        
        /// <remarks/>
        public nsiRef ServiceType { get; set; } 
        
        /// <remarks/>
        public decimal Rate { get; set; } 
        
        /// <remarks/>
        public decimal TotalPayable { get; set; } 
        
        /// <remarks/>
        public decimal AccountingPeriodTotal { get; set; } 
        
        /// <remarks/>
        public string CalcExplanation { get; set; } 
        
        /// <remarks/>
        public string orgPPAGUID { get; set; } 
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class PDServiceChargeExportType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalService", typeof(PDServiceChargeExportTypeAdditionalService))]
        [System.Xml.Serialization.XmlElementAttribute("HousingService", typeof(PDServiceChargeExportTypeHousingService))]
        [System.Xml.Serialization.XmlElementAttribute("MunicipalService", typeof(PDServiceChargeExportTypeMunicipalService))]
        public ServicePDType Item { get; set; } 
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class PDServiceChargeExportTypeAdditionalService : ServicePDType
    {
        
        /// <remarks/>
        public ServiceChargeType ServiceCharge { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Volume", IsNullable=false)]
        public PDServiceChargeExportTypeAdditionalServiceVolume[] Consumption { get; set; } 
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class PDServiceChargeExportTypeAdditionalServiceVolume
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PDServiceChargeExportTypeAdditionalServiceVolumeType type { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value { get; set; } 
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public enum PDServiceChargeExportTypeAdditionalServiceVolumeType
    {
        
        /// <remarks/>
        I,
        
        /// <remarks/>
        O,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class PDServiceChargeExportTypeHousingService : ServicePDType
    {
        
        /// <remarks/>
        public ServiceChargeType ServiceCharge { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MunicipalResource")]
        public PDServiceChargeExportTypeHousingServiceMunicipalResource[] MunicipalResource { get; set; } 
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class PDServiceChargeExportTypeHousingServiceMunicipalResource
    {
        
        /// <remarks/>
        public nsiRef ServiceType { get; set; } 
        
        /// <remarks/>
        public PDServiceChargeExportTypeHousingServiceMunicipalResourceConsumption Consumption { get; set; } 
        
        /// <remarks/>
        public decimal Rate { get; set; } 
        
        /// <remarks/>
        public decimal AccountingPeriodTotal { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccountingPeriodTotalSpecified { get; set; } 
        
        /// <remarks/>
        public ServiceChargeType ServiceCharge { get; set; } 
        
        /// <remarks/>
        public decimal MunicipalServiceCommunalConsumptionPayable { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MunicipalServiceCommunalConsumptionPayableSpecified { get; set; } 
        
        /// <remarks/>
        public PDServiceChargeExportTypeHousingServiceMunicipalResourceServiceInformation ServiceInformation { get; set; } 
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class PDServiceChargeExportTypeHousingServiceMunicipalResourceConsumption
    {
        
        /// <remarks/>
        public PDServiceChargeExportTypeHousingServiceMunicipalResourceConsumptionVolume Volume { get; set; } 
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class PDServiceChargeExportTypeHousingServiceMunicipalResourceConsumptionVolume
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PDServiceChargeExportTypeHousingServiceMunicipalResourceConsumptionVolumeType type { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PDServiceChargeExportTypeHousingServiceMunicipalResourceConsumptionVolumeDeterminingMethod determiningMethod { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool determiningMethodSpecified { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value { get; set; } 
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public enum PDServiceChargeExportTypeHousingServiceMunicipalResourceConsumptionVolumeType
    {
        
        /// <remarks/>
        O,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public enum PDServiceChargeExportTypeHousingServiceMunicipalResourceConsumptionVolumeDeterminingMethod
    {
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        M,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class PDServiceChargeExportTypeHousingServiceMunicipalResourceServiceInformation
    {
        
        /// <remarks/>
        public decimal houseOverallNeedsNorm { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool houseOverallNeedsNormSpecified { get; set; } 
        
        /// <remarks/>
        public decimal houseTotalHouseOverallNeeds { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool houseTotalHouseOverallNeedsSpecified { get; set; } 
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class PDServiceChargeExportTypeMunicipalService : ServicePDType
    {
        
        /// <remarks/>
        public ServiceChargeType ServiceCharge { get; set; } 
        
        /// <remarks/>
        public PiecemealPayment PiecemealPayment { get; set; } 
        
        /// <remarks/>
        public PDServiceChargeExportTypeMunicipalServicePaymentRecalculation PaymentRecalculation { get; set; } 
        
        /// <remarks/>
        public ServiceInformation ServiceInformation { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Volume", IsNullable=false)]
        public PDServiceChargeExportTypeMunicipalServiceVolume[] Consumption { get; set; } 
        
        /// <remarks/>
        public PDServiceChargeExportTypeMunicipalServiceMultiplyingFactor MultiplyingFactor { get; set; } 
        
        /// <remarks/>
        public decimal MunicipalServiceIndividualConsumptionPayable { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MunicipalServiceIndividualConsumptionPayableSpecified { get; set; } 
        
        /// <remarks/>
        public decimal MunicipalServiceCommunalConsumptionPayable { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MunicipalServiceCommunalConsumptionPayableSpecified { get; set; } 
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class PiecemealPayment
    {
        
        /// <remarks/>
        public decimal paymentPeriodPiecemealPaymentSum { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool paymentPeriodPiecemealPaymentSumSpecified { get; set; } 
        
        /// <remarks/>
        public decimal pastPaymentPeriodPiecemealPaymentSum { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pastPaymentPeriodPiecemealPaymentSumSpecified { get; set; } 
        
        /// <remarks/>
        public decimal piecemealPaymentPercentRub { get; set; } 
        
        /// <remarks/>
        public decimal piecemealPaymentPercent { get; set; } 
        
        /// <remarks/>
        public decimal piecemealPaymentSum { get; set; } 
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class PDServiceChargeExportTypeMunicipalServicePaymentRecalculation
    {
        
        /// <remarks/>
        public string recalculationReason { get; set; } 
        
        /// <remarks/>
        public decimal sum { get; set; } 
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class ServiceInformation : ServiceInformationType
    {
        
        /// <remarks/>
        public decimal houseOverallNeedsNorm { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool houseOverallNeedsNormSpecified { get; set; } 
        
        /// <remarks/>
        public decimal individualConsumptionNorm { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool individualConsumptionNormSpecified { get; set; } 
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class PDServiceChargeExportTypeMunicipalServiceVolume
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PDServiceChargeExportTypeMunicipalServiceVolumeType type { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PDServiceChargeExportTypeMunicipalServiceVolumeDeterminingMethod determiningMethod { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool determiningMethodSpecified { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value { get; set; } 
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public enum PDServiceChargeExportTypeMunicipalServiceVolumeType
    {
        
        /// <remarks/>
        I,
        
        /// <remarks/>
        O,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public enum PDServiceChargeExportTypeMunicipalServiceVolumeDeterminingMethod
    {
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        O,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class PDServiceChargeExportTypeMunicipalServiceMultiplyingFactor
    {
        
        /// <remarks/>
        public decimal Ratio { get; set; } 
        
        /// <remarks/>
        public decimal AmountOfExcessFees { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountOfExcessFeesSpecified { get; set; } 
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class PaymentDocumentExportTypeChargeDebt : PDServiceDebtType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class PaymentDocumentExportTypeInsurance
    {
        
        /// <remarks/>
        public string InsuranceProductGUID { get; set; } 
        
        /// <remarks/>
        public decimal Rate { get; set; } 
        
        /// <remarks/>
        public decimal TotalPayable { get; set; } 
        
        /// <remarks/>
        public decimal AccountingPeriodTotal { get; set; } 
        
        /// <remarks/>
        public string CalcExplanation { get; set; } 
        
        /// <remarks/>
        public ServiceChargeType ServiceCharge { get; set; } 
        
        /// <remarks/>
        public PaymentDocumentExportTypeInsuranceConsumption Consumption { get; set; } 
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class PaymentDocumentExportTypeInsuranceConsumption
    {
        
        /// <remarks/>
        public PaymentDocumentExportTypeInsuranceConsumptionVolume Volume { get; set; } 
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class PaymentDocumentExportTypeInsuranceConsumptionVolume
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PaymentDocumentExportTypeInsuranceConsumptionVolumeType type { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified { get; set; } 
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value { get; set; } 
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public enum PaymentDocumentExportTypeInsuranceConsumptionVolumeType
    {
        
        /// <remarks/>
        I,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public partial class PaymentDocumentExportTypePenaltiesAndCourtCosts
    {
        
        /// <remarks/>
        public nsiRef ServiceType { get; set; } 
        
        /// <remarks/>
        public string Cause { get; set; } 
        
        /// <remarks/>
        public decimal TotalPayable { get; set; } 
        
        /// <remarks/>
        public string orgPPAGUID { get; set; } 
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills/", IncludeInSchema=false)]
    public enum ItemChoiceType1
    {
        
        /// <remarks/>
        Expose,
        
        /// <remarks/>
        Withdraw,
    }
}
